{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.26.0" %}
{% set sha256 = "a65b67a9a6b06ba1ec406114568e21afe88c1cdb29c464f2507d529eb906d8ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_grpc-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.dev0
    - grpcio >=1.0.0,<2.0.0
    - opentelemetry-api >=1.15,<2.dev0
    - opentelemetry-proto ==1.26.0
    - opentelemetry-sdk >=1.26.0,<1.27.dev0
    - opentelemetry-exporter-otlp-proto-common ==1.26.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / Protobuf over gRPC Exporter
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io/en/latest/
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  recipe-maintainers:
    - mariusvniekerk
