{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2473935e9eac71f401de6101d37d6f3f0f1831db92b953c7dcc912536158ebd6

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - googleapis-common-protos >=1.57,<2
    - grpcio >=1.63.2,<2.0.0  # [py<313]
    - grpcio >=1.66.2  # [py>=313]
    - opentelemetry-api >=1.15,<2
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk >=1.38.0,<1.39.0.dev
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
    - typing-extensions >=4.6.0

# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
{% set ignore_tests = " --ignore=tests/test_otlp_metrics_exporter.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_otlp_trace_exporter.py" %}
# Disabled unstable tests with timeouts:
{% set deselect_tests = " --deselect=tests/test_otlp_exporter_mixin.py::TestOTLPExporterMixin::test_retry_info_is_respected" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_otlp_exporter_mixin.py::TestOTLPExporterMixin::test_timeout_set_correctly" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_otlp_exporter_mixin.py::TestOTLPExporterMixin::test_shutdown_interrupts_export_retry_backoff" %}

test:
  source_files:
    - tests
  imports:
    - opentelemetry.exporter.otlp.proto.grpc
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: OpenTelemetry Python / Protobuf over gRPC Exporter
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.
  doc_url: https://opentelemetry-python.readthedocs.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc

extra:
  recipe-maintainers:
    - mariusvniekerk
