{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-otlp-proto-grpc-{{ version }}.tar.gz
  sha256: b69a5b080cabcb4e69e5fb27f697def3fb59685b11360fa2db01bea827b9cc97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - backoff <3.0.0,>=1.10.0
    - googleapis-common-protos ~=1.52
    - grpcio <2.0.0,>=1.0.0
    - opentelemetry-api ~=1.3
    - opentelemetry-proto ==1.12.0
    - opentelemetry-sdk ~=1.11
    - python >=3.6
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 
    # - pytest-grpc 

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  summary: OpenTelemetry Collector Protobuf over gRPC Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
