{% set name = "opentelemetry-exporter-otlp-proto-grpc" %}
{% set version = "1.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_grpc-{{ version }}.tar.gz
  sha256: d0f10f0b9b9a383b7d04a144d01cb280e70362cccc613987e234183fd1f01177

build:
  number: 0
  skip: true  # [py<38]
  skip: true  # [s390x]   
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.dev0
    - grpcio >=1.63.2,<2.0.0
    - opentelemetry-api >=1.15,<2.dev0
    - opentelemetry-proto ==1.30.0
    - opentelemetry-sdk >=1.30.0,<1.31.dev0
    - opentelemetry-exporter-otlp-proto-common ==1.30.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / Protobuf over gRPC Exporter
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-grpc
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  recipe-maintainers:
    - mariusvniekerk
